# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: rick@mcgeer.com
author_name: Rick McGeer
has_binder: false
has_settings: false
kind: frontend
labextension_name: omni_engineer_extension
project_short_description: Extending JupyterLab to incorporate Omni Engineer
python_name: omni_engineer_extension
repository: https://github.com/rickmcgeer/omni-engineer-extension
test: false

